name: geodiary
description: A location-based journaling app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  firebase_analytics: ^11.4.5

  geolocator: ^13.0.4

  flutter_local_notifications: ^19.0.0

  intl: ^0.20.2
  google_fonts: ^6.2.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

flutter:
  uses-material-design: true